BASE_PATH : /blob/master
collections:
  projects:
    output: true


defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

github_username: TheExGenesis
twitter_username: ExGenesis
instagram_username: theexgenesis

color_scheme: github

google_analytics: UA-NNNNNNNN-N

mathjax: true

